cuda: 0
batch_size: 2

# Model specific config -- Example
model: 
  num_layers: 6

# Training specific config - optimizer, lr scheduler, etc.
training:
  total_epochs: 2
  lr: 0.001

# Data directory config
data_dir:
  input_dir: 
    train_path: "data/sample_train_data.pt"
    valid_path: "data/sample_valid_data.pt"
    test_path: "data/sample_test_data.pt"

# Training output directory config
training_dir:
  output_dir: "results/custom_model"

# Eval output directory config - fill after training
eval_dir:
  eval_output_dir: "results/custom_model/12-05_14-02-43"
  best_model_path: "results/custom_model/12-05_14-02-43/training_results/checkpoints/best_model.pth"
 
accelerator:
  project_dir: "results/custom_model_acc/"
  log_with: "tensorboard"
  gradient_accumulation_steps: 4
  mixed_precision: "no"
  ddp_find_unused_parameters: true